runtime: go
api_version: go1.9
service: speedtest-logging

env_variables:
  GIN_MODE: release

skip_files:
  - ^vendor/.*$
  - ^app\.yaml$
  - ^Gopkg.*$

handlers:
  - url: /(.*\.(txt))$
    static_files: static/\1
    upload: static/.*\.(txt)$
  - url: /.*
    script: _go_app
    secure: always
    redirect_http_response_code: 301
